In [1]:
import numpy as np
import pandas as pd

In [22]:
data = pd.read_csv("chicago-ssl-clean.csv")

In [23]:
age_d = {'less than 20': (14, 20), '20-30': (20, 30), '30-40': (30, 40), '40-50': (40, 50), '50-60': (50, 60), '60-70': (60, 70), '70-80': (70, 80) }
data['PREDICTOR RAT AGE AT LATEST ARREST'] = data['PREDICTOR RAT AGE AT LATEST ARREST'].apply(lambda x: np.random.randint(*age_d[x]))

In [24]:
data

,SSL SCORE,PREDICTOR RAT AGE AT LATEST ARREST,PREDICTOR RAT VICTIM SHOOTING INCIDENTS,PREDICTOR RAT VICTIM BATTERY OR ASSAULT,PREDICTOR RAT ARRESTS VIOLENT OFFENSES,PREDICTOR RAT GANG AFFILIATION,PREDICTOR RAT NARCOTIC ARRESTS,PREDICTOR RAT TREND IN CRIMINAL ACTIVITY,PREDICTOR RAT UUW ARRESTS,SEX CODE CD,RACE CODE CD
0,500,22,0,1,4,1,1,1.0,1,M,BLK
1,500,28,0,9,1,1,0,1.0,0,M,WHI
2,500,18,1,2,1,1,3,1.0,0,M,WHI
3,500,17,1,1,4,1,0,1.6,1,M,BLK
4,500,16,0,0,5,0,0,1.3,3,M,BLK
...,...,...,...,...,...,...,...,...,...,...,...
398577,310,42,1,1,1,0,0,-0.1,0,F,I
398578,269,32,0,0,0,1,0,0.3,0,M,BLK
398579,86,70,0,0,0,0,1,0.1,0,M,BLK
398580,245,40,0,0,0,1,1,-0.1,0,M,WWH
398581,321,20,0,0,0,0,0,0.3,0,M,WWH

In [25]:
data['SSL SCORE'] = data['SSL SCORE'].apply(lambda x: 0 if x > 345 else 1)

In [26]:
data.drop(columns=['PREDICTOR RAT GANG AFFILIATION', 'SEX CODE CD'], inplace=True)

In [27]:
data['RACE CODE CD'] = data['RACE CODE CD'].apply(lambda x: 'w' if x in ['WHI', 'WWH'] else 'nw')

In [28]:
data

,SSL SCORE,PREDICTOR RAT AGE AT LATEST ARREST,PREDICTOR RAT VICTIM SHOOTING INCIDENTS,PREDICTOR RAT VICTIM BATTERY OR ASSAULT,PREDICTOR RAT ARRESTS VIOLENT OFFENSES,PREDICTOR RAT NARCOTIC ARRESTS,PREDICTOR RAT TREND IN CRIMINAL ACTIVITY,PREDICTOR RAT UUW ARRESTS,RACE CODE CD
0,0,22,0,1,4,1,1.0,1,nw
1,0,28,0,9,1,0,1.0,0,w
2,0,18,1,2,1,3,1.0,0,w
3,0,17,1,1,4,0,1.6,1,nw
4,0,16,0,0,5,0,1.3,3,nw
...,...,...,...,...,...,...,...,...,...
398577,1,42,1,1,1,0,-0.1,0,nw
398578,1,32,0,0,0,0,0.3,0,nw
398579,1,70,0,0,0,1,0.1,0,nw
398580,1,40,0,0,0,1,-0.1,0,w
398581,1,20,0,0,0,0,0.3,0,w

In [32]:
new_cols = list(data.columns)[1:] + ['SSL SCORE']

In [33]:
data = data[new_cols]

In [34]:
data

,PREDICTOR RAT AGE AT LATEST ARREST,PREDICTOR RAT VICTIM SHOOTING INCIDENTS,PREDICTOR RAT VICTIM BATTERY OR ASSAULT,PREDICTOR RAT ARRESTS VIOLENT OFFENSES,PREDICTOR RAT NARCOTIC ARRESTS,PREDICTOR RAT TREND IN CRIMINAL ACTIVITY,PREDICTOR RAT UUW ARRESTS,RACE CODE CD,SSL SCORE
0,22,0,1,4,1,1.0,1,nw,0
1,28,0,9,1,0,1.0,0,w,0
2,18,1,2,1,3,1.0,0,w,0
3,17,1,1,4,0,1.6,1,nw,0
4,16,0,0,5,0,1.3,3,nw,0
...,...,...,...,...,...,...,...,...,...
398577,42,1,1,1,0,-0.1,0,nw,1
398578,32,0,0,0,0,0.3,0,nw,1
398579,70,0,0,0,1,0.1,0,nw,1
398580,40,0,0,0,1,-0.1,0,w,1
398581,20,0,0,0,0,0.3,0,w,1

In [13]:
data.to_csv("ssl_numeric.csv", index=False)

In [38]:
data.columns

Index(['SSL SCORE', 'PREDICTOR RAT VICTIM SHOOTING INCIDENTS',
       'PREDICTOR RAT VICTIM BATTERY OR ASSAULT',
       'PREDICTOR RAT ARRESTS VIOLENT OFFENSES',
       'PREDICTOR RAT NARCOTIC ARRESTS',
       'PREDICTOR RAT TREND IN CRIMINAL ACTIVITY', 'PREDICTOR RAT UUW ARRESTS',
       'RACE CODE CD'],
      dtype='object')